from playwright.sync_api import sync_playwright
from pages.signup_page import SignupPage
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    signup = SignupPage(page)
    signup.open()
    signup.click_signin()
    signup.wait(2000)
    signup.enter_email("maniking22806@gmail.com")
    signup.click_continue()
    signup.wait(2000)
    signup.enter_first_name("Pradeep")
    signup.enter_last_name("M")
    signup.enter_phone("9361358104")
    signup.enter_password("Pnex@gt2")
    signup.enter_confirm_password("Pnex@gt2")
    signup.accept_terms()
    signup.click_signup()
    signup.wait(5000)
    print(signup.get_url())
    print(signup.get_title())
    print(signup.page.locator("body").inner_text())
    browser.close()